### ISSUE TITLE
Anotações

### ISSUE THREAD

**Issue by danfma** [kaichiro/PosUFG-PFEA#1]
- Não implementou o carousel;
- Não implementou o menu de seleção de categorias;
- É uma boa prática criar action creators para evitar espalhar no seu código a lógica de criação das ações;
- Alguns componentes possuem a lógica para efetuar o fetch de dados. Apesar de ser uma prática comum, não é uma boa prática, visto que a lógica para obter dados é considerada lógica de domínio;

![image](https://user-images.githubusercontent.com/101121/55291946-25d1b180-53bb-11e9-8652-052e0e689e52.png)

**Comment by kaichiro** [comment]
- Tentamos implementar um componente de carrossel bem simples e reaproveita-lo em outras partes do projeto, no entanto, não conseguimos dominar todo o componente a tempo de entrega, mas conseguimos colocá-lo no projeto;
![teste](https://user-images.githubusercontent.com/19508753/55364436-04ee8680-54b7-11e9-90e2-2de3686bf9bb.gif)

 - Não implementamos o menu para escolha de categorias;
 - Estudando mais afundo o controle do estado, percebemos que não implementamos práticas de boas maneiras para este controle.
 - Detalhe, não consegui simular o erro.
